backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "cms/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts/blog"
    extension: "json"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", dateFormat: "DD.MM.YYYY", timeFormat: "HH:mm", format: "LLL"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
      - label: "Links to project"
        name: "linksToProject"
        widget: "object"
        fields:
          - {label: "Github", name: "github", widget: "string", required: false}
          - {label: "Web", name: "web", widget: "string", required: false}