on:
  pull_request:
  push:
    branches: master

jobs:
  merge_job:
    runs-on: ubuntu-latest
    name: Merge posts into one json file
    steps:
    - uses: actions/checkout@v1
    - name: Merge files action step
      uses: ./.github/actions/merge
    - name: Push step
      uses: ./.github/actions/push
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        some_other: "HELLO"
