on:
  pull_request:
  push:
    branches: master

jobs:
  merge_job:
    runs-on: ubuntu-latest
    name: Merge posts into one json file
    steps:
    - name: Merge files action step
      working-directory: ./.github/actions/merge
      run: bash merge.sh
    - name: Push step
      working-directory: ./.github/actions/push
      run: bash push.sh
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
