on:
  pull_request:
  push:
    branches: master

jobs:
  merge_job:
    runs-on: ubuntu-latest
    name: Merge posts into one json file
    steps:
    - name: Merge files action step
      id: merge
      run: pwd
