on:
  pull_request:
  push:
    branches: master

jobs:
  merge_job:
    runs-on: ubuntu-latest
    name: Merge posts into one json file
    steps:
    - name: Merge files action step
      id: merge
      uses: actions/merge
    - name: Push the changes
      uses: actions/push
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
