# on:
#   pull_request:
#     types: [closed]
#     branches: [ master ]

on:
  push:
    branches: master

jobs:
  merge_job:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged
    name: Merge posts into one json file
    steps:
    - uses: actions/checkout@v1
    - name: Merge files action step
      uses: ./.github/actions/merge
    - name: Commit Changes
      run: |
        git config --local user.email "${{secrets.EMAIL}}"
        git config --local user.name "${{secrets.NAME}}"
        git commit -m "Merge json files - Action" -a
    - name: Push step
      uses: ./.github/actions/push
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
